---
application:
  name: "coffeebot"
  project: "DeployMyApp"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "my-psql"
  version: "12"
routers:
- name: "main-coffeebot"
  routes:
  - application_name: "coffeebot"
    paths:
    - "/*"
